version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.11
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: evgenmater/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    image: evgenmater/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: evgenmater/foodgram_gateway
    env_file: .env
    volumes:
      - static:/static/
      - media:/app/media
    depends_on:
      - backend
    ports:
      - 9090:80