# Generated by Django 3.2.3 on 2023-10-11 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20231011_2334'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_name_color_slug',
        ),
    ]
